### ISSUE TITLE
Führende 0 in Telefonnummer in den Userdaten wird abgeschnitten.

### ISSUE THREAD

**Issue by tabacha** [ADFC-Hamburg/adfc-t30-api#19]
Wenn man eine Telefonnummer mit einer führenden Null z.B 040112 eingibt, wird nach dem nächsten laden daraus 40112

Testinstanz:

https://tools.adfc-hamburg.de/t30-paten/version0.0.16/#/login

**Comment by bensteffen** [comment]
Jo, ist schon gefixt, werde ein Pull-Request aufmachen
