### ISSUE TITLE
Wie lautet der API Call um die Liste aller Institutionen zu bekommen, zusammen mit dem Bezirksnamen in der die Einrichtung liegt?

### ISSUE THREAD

**Issue by tabacha** [ADFC-Hamburg/adfc-t30-api#39]

**Comment by tabacha** [comment]
Query:

 select i.*,d.name from institution i, districthamburg d  where ST_Contains(d.geom,i.position)  and i.id<10 order by i.id;

**Comment by bensteffen** [comment]
Moin,

am Call

GET /api/crud.php?entity=institution

ändert sich nichts. Siehe Pull-Request https://github.com/ADFC-Hamburg/adfc-t30-api/pull/44
