### ISSUE TITLE
Positionsänderung wird nicht richtig per E-Mail übermittelt

### ISSUE THREAD

**Issue by tabacha** [ADFC-Hamburg/adfc-t30-api#40]
Hallo,

am 16.09.2019 um 11:46:11

wurde(n) durch 'admin'

im Datensatz 'institution' mit ID 1169 folgendende Änderung(en) durchgeführt:

* Attribut 'position': Array => Array

**Comment by bensteffen** [comment]
Gelöst: Gibt update in den bs-utils.
