### ISSUE TITLE
Verbindung: User -> Userdata. Irgendwass passt da noch nicht

### ISSUE THREAD

**Issue by tabacha** [ADFC-Hamburg/adfc-t30-api#42]
Ich habe mich als Admin angemeldet.

Editiere ich nun die Userdaten, werden diese mit der ID 1 als Max-Muster gespeichert.

```
MariaDB [t30]> select * from user;
+-----------------------------+--------------------------------------------------------------+------------+
| name                        | password                                                     | isVerified |
+-----------------------------+--------------------------------------------------------------+------------+
| admin                       | $2y$10$LYPu4Jk/LHaAkbfgLhSvJuh8udgo3Kt0.y1S6zS31G0/QOn2.N3Au |          1 |
| guest                       | $2y$10$Ox4N5WgLNE08Rw66ZKDaTeFTUgPJ4Ebk2qztVWtZnAmcnq3IJGpPC |          1 |
| max-muster@some-provider.de | $2y$10$.aPxu1JbL0F11MoOfnhg0uzlkta0CxyRkE53NciaNdU1IgXsm7Rn2 |          1 |
+-----------------------------+--------------------------------------------------------------+------------+
3 rows in set (0.000 sec)

MariaDB [t30]> select * from userdata;
+----+-----------------------------+-----------------+-------+---------+-------+--------+
| id | user                        | street_house_no | zip   | city    | phone | mobile |
+----+-----------------------------+-----------------+-------+---------+-------+--------+
|  1 | max-muster@some-provider.de | Fakestreet 123  | 22666 | Hamburg | NULL  | NULL   |
+----+-----------------------------+-----------------+-------+---------+-------+--------+
1 row in set (0.000 sec)

MariaDB [t30]> select * from roleasignement;
ERROR 1146 (42S02): Table 't30.roleasignement' doesn't exist
MariaDB [t30]> select * from roleassignment;
+------------+-----------------------------+
| role       | user                        |
+------------+-----------------------------+
| admin      | admin                       |
| guest      | guest                       |
| guest      | max-muster@some-provider.de |
| registered | max-muster@some-provider.de |
+------------+-----------------------------+
4 rows in set (0.000 sec)
```

**Comment by bensteffen** [comment]
Was genau meinst du mit editieren?

Ich glaube das Ding ist, dass admin und guest keine Benutzer sind, hinter denen eine reale Person steht. Deswegen gibt es für die keine User-Daten.

Könntest Du das Problem noch mal genauer erklären?

**Comment by tabacha** [comment]
Wieso ist der Admin kein richtiger User? Ich will Leute, die sich für eine Kita/Schule einsetzen irgendwann ggf. zum Admin machen.

Ich  mache in der Gui einen GET /crud.php?entity=userdata&onlyOwn

Bekomme daten zurück und speichere die mit einem PUT /api/crud.php?entity=userdata

ich möchte das das immer funktioniert und das z.B. der Admin auch seine Mailadresse ändern kann.

Ansonsten brauche ich mindestens einen Api-Call ob jemand Admin ist.

**Comment by bensteffen** [comment]
admin ist schon ein richtiger User, aber keiner, dem eine bestimmte Person zuordnet ist. Ist nicht zu verwechseln mit der Rolle "admin", die allen Usern zugeordnet werden kann. Man braucht aber einen User mit der Rolle admin, um Rollen zuordnen zu können. Eigentlich v.a. wegen diesem Henne-Ei-Problem gibt es den User "admin". 

Wie man auf diese Krücke verzichten könnte: Man hinterlegt in der Config einen User (oder eine Liste von Usern bzw. Email-Adressen), denen beim Setup automatisch die Admin-Rolle zugeordnet wird. Dieser User kann dann wiederum weitere Admins bestimmen.

**Comment by bensteffen** [comment]
Rollenzuordnung ging so:

POST /api/portal.php
``` json
{
	"concern": "roleAdministration",
	"role": "admin",
	"assignTo": "user@der-admin-wird.de"
}
```
wobei man mit einem User angemeldet ist, dem die Rolle "admin" zuordnet ist.

**Comment by tabacha** [comment]
Okay. Wir machen im Live-System nur Leute mit E-Mailaddresse zum Admin
