### ISSUE TITLE
Token Verify

### ISSUE THREAD

**Issue by tabacha** [ADFC-Hamburg/adfc-t30-api#51]
Welchen API Call muss ich mit welchen Parametern aufrufen um eine Registrierung mit dem Code:

SLPSLG

abzuschließen?

Versuche im Moment:

portal.php?verify=SLPSLG

**Comment by bensteffen** [comment]
Bei den einfachen Token muss noch die Mail (bzw. der User) angegeben werden, die die der Token erstellt wurde:

GET /portal.php?verify=SLPSLG&user=mail@die-verifiziert-wird.de
