### ISSUE TITLE
Encoding falsch

### ISSUE THREAD

**Issue by tabacha** [ADFC-Hamburg/adfc-t30-api#54]
Speichert man etwas mit Sonderzeichen, wie z.B. Überseering, ist danach nach dem laden das Encoding defekt.

**Comment by tabacha** [comment]
Ist zuminst im Teil gefixt: https://github.com/ADFC-Hamburg/flexapi/pull/34

**Comment by bensteffen** [comment]
Was heißt zum Teil?

**Comment by tabacha** [comment]
Zum Teil heißt, das ich das nicht genauer untersucht habe, aber das Gefühl hatte, es würde helfen. Aber an das Thema mit dem Escapen müssen wir IMHO sowieso ran.
