### ISSUE TITLE
Mailversand

### ISSUE THREAD

**Issue by tabacha** [ADFC-Hamburg/adfc-t30-api#56]
Wenn die Url: api/crud.php?entity=email

mit PUT oder POST mit  Beispieldaten:

```
'{"id":1,"geprueft":"2","bezugZurEinrichtung":"aaaa","status_text":"assasa","mailSend":false,"sendMailNow":false,"password":"","mail_subject":"Tempo 30 fu00fcr aaaaa 11 111 an Max-Brauer-Schule ","mail_start":"Sehr geehrte Damen und Herren,\nmein Name ist Max Muster. Ich bin aaaa des Alten-, Pflege- und Tagespflegeheims \"Max-Brauer-Schule\", Bei der Paul-Gerhardt-Kirche 1, 22761 Hamburg.","mail_body":"Im Umfeld dieser Einrichtung fehlt leider noch Tempo 30.\n\nIch ersuche Sie hiermit, an diesem an die Schule angrenzenden Strau00dfenabschnitt  von Hausnummer 10 bis Hausnummer  Tempo 30 einzufu00fchren.\n\nBegru00fcndung:\nHaupteingang\n\n\n\n(gerne durch Beschreibungen der Umstu00e4nde vor Ort ergu00e4nzen)\n\nAus meiner Sicht sind die Kinder die im Umfeld der Schule am Verkehr teilnehmen, nicht ausreichend vor dem schnellen KFZ-Verkehr geschu00fctzt.\nDie KFZ-Fahrer*innen mu00fcssen durch ein geringeres Tempo in die Lage versetzt werden, besondere Aufmerksamkeit walten zu lassen.\nDie u00c4nderung fu00fcr den KFZ-Verkehrhalte ich angesichts des Sicherheitsgewinns fu00fcr angemessen. Der Sicherheit muss Vorrang vor Geschwindigkeit gewu00e4hrt werden.\n\n\n\nLaut u00a745 Absatz 9 Satz 4 Ziffer 6 der StVO in Verbindung mit der Verwaltungsvorschrift zu u00a745 StVO soll zum Schutz besonders schu00fctzenswerter Personen im Umfeld sozialer Einrichtungen,\nalso dort wo Haupteingu00e4nge sind oder Quell- und Zielverkehr zur Einrichtung herrscht, regulu00e4r Tempo 30 gelten, ohne dass eine besondere Gefahrenlage erwiesen ist.","mail_end":"Vielen Dank und mit freundlichen Gru00fcu00dfen\n\nMax Muster\n\nFakestreet 123\n22666 Hamburg\n\n\n--\nDiese E-Mail wurde durch das Tempo 30-Tool des ADFC-Hamburg verschickt, mehr Infos dazu unter\nhttps://hamburg.adfc.de/hast-nicht-gesehen-FIXME","person":1,"demanded_street_section":1}'

```
mit mailSendNow=true aufgerufen wird, soll eine Mail an das Polizeikommeseriat geschickt werden, das PK kann mit der Query:

SELECT p.id as id ,p.name as name ,p.email as email,i.name as institution FROM policedepartment p, institution i WHERE ST_CONTAINS(p.geom, i.position) AND i.id=?

ermittelt werden.

Für den Test bitte 
```
update policedepartment set email= REPLACE(email,'polizei.hamburg.de', 'sven.anders.hamburg');
```

Die E-Mail soll das Subject: mail_subject 
und den UTF8 Plain Text body:
mail_start+ mail_body + mail_end 
bekommen
und an den Antragssteller und an tempo30sozial@hamburg.adfc.de als CC geschickt werden.

**Comment by bensteffen** [comment]
Es scheint mir so, dass mit den Zuständigkeitsbereiche der Polizeikommissariate in unserer Tabelle (hab ich aus der dump.sql) etwas nicht stimmt. So liefert ST_CONTAINS für eine bestimmte Institution (hier mit Id = 1, welche nach der township-Tabelle in Harburg liegt) 

```sql
SELECT 
  policedepartment.name, policedepartment.region
FROM
  policedepartment
JOIN 
  institution 
ON
  institution.id = 1 AND ST_CONTAINS(policedepartment.geom,institution.position) 
WHERE
  1;
```

mehere PKs als Ergebnis, von denen nur eine als Region Harburg angegeben hat:

![image](https://user-images.githubusercontent.com/37374938/66143566-a8a42500-e607-11e9-9ac1-d92e0e6fe636.png)

**Comment by tabacha** [comment]
Wie sieht denn  ST_AsText(geom) und ST_AsText(position) aus?Wenn die 
Geometry defekt ist, gibt es solche Phänomene.

Gruß Sven


Am 3. Oktober 2019 18:02:44 schrieb bensteffen <notifications@github.com>:

**Comment by bensteffen** [comment]
````sql
SELECT p.name, p.geom FROM policedepartment p;
```
sieht gut aus:
name	geom	
WSPK 1	[GEOMETRY - 39,2 KiB]	
WSPK 2	[GEOMETRY - 162,8 KiB]	
WSPK 3	[GEOMETRY - 106,7 KiB]	
PK 11	[GEOMETRY - 6,8 KiB]	
PK 14	[GEOMETRY - 27,9 KiB]	
PK 15	[GEOMETRY - 4,7 KiB]	
PK 16	[GEOMETRY - 8,2 KiB]	
PK 17	[GEOMETRY - 12,1 KiB]	
PK 21	[GEOMETRY - 15,6 KiB]	
PK 23	[GEOMETRY - 24,4 KiB]	
PK 24	[GEOMETRY - 19,9 KiB]	
PK 25	[GEOMETRY - 23,8 KiB]	
PK 26	[GEOMETRY - 27,6 KiB]	
PK 27	[GEOMETRY - 17,9 KiB]	
PK 31	[GEOMETRY - 18,5 KiB]	
PK 33	[GEOMETRY - 17,6 KiB]	
PK 34	[GEOMETRY - 17,8 KiB]	
PK 35	[GEOMETRY - 75,7 KiB]	
PK 36	[GEOMETRY - 15,7 KiB]	
PK 37	[GEOMETRY - 7,0 KiB]	
PK 38	[GEOMETRY - 32,3 KiB]	
PK 41	[GEOMETRY - 32,2 KiB]	
PK 42	[GEOMETRY - 27,4 KiB]	
PK 43	[GEOMETRY - 85,7 KiB]	
PK 44	[GEOMETRY - 43,6 KiB]	

Als Text wird geom bei vielen PKs aber als NULL dargestellt
```sql
SELECT p.name, ST_ASTEXT(p.geom) FROM policedepartment p;
```

name	ST_ASTEXT(p.geom)	
WSPK 1	NULL	
WSPK 2	NULL	
WSPK 3	NULL	
PK 11	NULL	
PK 14	NULL	
PK 15	NULL	
PK 16	MULTIPOLYGON(((-1.3016459533881764e228 -1.80418033...	
PK 17	NULL	
PK 21	MULTIPOLYGON(((-6.871579633450773e227 -0.000000000...	
PK 23	NULL	
PK 24	NULL	
PK 25	NULL	
PK 26	MULTIPOLYGON(((-3.010788042066646e229 1.6692676597...	
PK 27	NULL	
PK 31	NULL	
PK 33	NULL	
PK 34	NULL	
PK 35	NULL	
PK 36	MULTIPOLYGON(((2.7529604809327454e225 -1.385864632...	
PK 37	MULTIPOLYGON(((1.1281352173379045e-66 -0.991912810...	
PK 38	NULL	
PK 41	NULL	
PK 42	NULL	
PK 43	NULL	
PK 44	NULL	
PK 46	MULTIPOLYGON(((-0.000000000029045346162564637 -0.0...	
PK 47	NULL	

Die PKs, bei denen geom nicht NULL ist sind genau die, bei denen ST_CONTAINS oben einen Treffer hatte.

**Comment by bensteffen** [comment]
Hier ein Ausschnitt aus dem Polygon von PK 16 (die Zahlenwerte sind viel zu extrem, oder?):

MULTIPOLYGON(((-1.3016459533881764e228 -1.804180330428463e230,-6.015478845536096e228 -0.000000000029044228843373156,-0.000000000029046067630917963 -0.00000000002904606763088379,-0.00000000002904476300038992 3.025012665307396e262,-0.9765795427369719 -0.00000000002904606763090166,-0.9765981393861508 -4.820669363044107e229,-0.000000000029044672924324435 -139946852318.48605,-0.9919128107956576 2.4092134313740964e-26,-0.000000000029044326554342904 1.598840737093523e-136,-0.000000000029046067630831772 -7.718981727043719e227,-1.2392114841746546e228 1.4226142873313715e-278,-0.9762099939393762 1.1328366293152658e25,-0.9919128115125185 -1.804180236846266e230,1.1130700832882491e52 -0.000000000029044249522241205,-0.9919128115125185 -1.8798371392079453e227,-0.9767750500449707 2.0532520968550169e71,1.5988405942902986e-136

**Comment by tabacha** [comment]
Ich vermute, du benutzt das falsche Dump File. Bei mir sind die alle definiert. Und die Werte sollten mit Koordinaten aus Hamburg (also 10...  50...) oder so sein 

Ich habe das Dump-File wegen Continuos Deployment noch unter:
https://tools.adfc-hamburg.de/t30-paten/daten/geodaten.sql
abgelegt.

**Comment by tabacha** [comment]
Evtl. liegt es auch daran, dass das Dumpfile nicht für deine Mysql/Maria/ProzessorArchitektur Version funktioniert. Wenn dem so ist, müsstes du mit prepare_geodata.sh selbst dir einen Dump erzeugen.

Ich nutze Mariadb 10.3

**Comment by bensteffen** [comment]
Alles klar, ich hatte eine falsches Dump-File, jetzt siehts gut aus!
