### ISSUE TITLE
Wie bekomme ich userdata vom aktuell eingeloggten User?

### ISSUE THREAD

**Issue by tabacha** [ADFC-Hamburg/adfc-t30-api#6]
Ich mache im Moment:

```
 curl 'http://localhost:4200/t30/api/crud.php?entity=userdata'   -H 'Access-Control-Allow-Credentials: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE1NjM0NTEzNDksImp0aSI6IjY3ODg1MGViZDNhODliNzk0NjVjYjU0YWQ2MjZjMzg2ZTYxNTNiNWJkOGUwMjU2NDBlY2UwYjM1OGYzMGJlZmIiLCJleHAiOjE1NjM0NTQ5NDksImRhdGEiOnsidXNlcm5hbWUiOiJtYXgtbXVzdGVyQHNvbWUtcHJvdmlkZXIuZGUifX0.fvcqP5YydBzQalbSv6V8Y5N06Pcmeqv982JYk0qqHptg7MjzmAbl1jKp3twIhzrf344lPOXQqzjnF7UnWV8dwQ'  -X GET
```

Was mir eine Liste aller User zurückliefert. Ich möchte aber nur den eingeloggten. Bitte Dokumentieren am besten in der Readme.md

**Comment by tabacha** [comment]
Hab gerade herausgefunden, dass im JWT Token die E-Mail drinssteht und ich danach filtern kann. Ist zwar nicht hübsch, aber geht

**Comment by bensteffen** [comment]
Hm das ist komisch. Bei mir funktioniert es ohne Filter nur mit Übergabe des JWTs.

**Comment by bensteffen** [comment]
Du könntest mal checken ob in der Tabelle "permission" für jeden Benutzer entsprechende Einträge für Lesen und Updaten ( = RU) zu finden sind.

![image](https://user-images.githubusercontent.com/37374938/61655220-659c0c00-acbe-11e9-9033-417a00e196fd.png)

Und die Tabelle "crudpermission" sollte so aussehen;

![image](https://user-images.githubusercontent.com/37374938/61655343-b3187900-acbe-11e9-9c90-4d2a5ec1eb4c.png)

**Comment by bensteffen** [comment]
Was mir noch eingefallen ist: Hast du vlt einen JWT des Admins verwendet? Dann bekommt man tatsächlich die Benutzer-Daten aller User zurück...

**Comment by tabacha** [comment]
Das ist schon richtig. Für einen normalen User geht es. Wobei halt ein Array mit einem Entry und kein Entry zurück kommt.

Aber wie ändert dann ein Admin seine Profildaten?

Aber mit dem Filter sollte das dann ja gehen. Oder siehst du da Bedarf für einen neuen API Call?

**Comment by bensteffen** [comment]
Ok alles klar, es geht um Profildaten für den Admin. Das hatte ich noch nicht auf dem Schirm.  Da können wir nochmal drüber nachdenken, ob es einen Benutzer Admin gibt oder man bestimmten Benutzern eine Rolle Admin zuordnen kann.

**Comment by tabacha** [comment]
Ich denke das letztere, ich sehe da uns (als Softwareentwickler), Wiebke, Jens, evtl. noch mehr aus der ADFC Gst. die sinnvollerweise Dinge tun können sollten, die normale User nicht können.

**Comment by bensteffen** [comment]
Ok. Man bräuchte dafür wohl eine Art Super-Admin, mit dem man (zumindest initial) die Admin-Rolle  oder auch andere Rollen vergeben kann.

Oder man könnte bestimmte E-Mail-Adresse  in der Konfig. festhalten, die dann nach der Verifizierung die Admin-Rolle zugeordnet bekommen.

**Comment by bensteffen** [comment]
> Das ist schon richtig. Für einen normalen User geht es. Wobei halt ein Array mit einem Entry und kein Entry zurück kommt.

Hierfür gibt es den Query-Parameter "flatten=singeResult". Also z. B.

GET /api/crud.php?entity=userdata&flatten=singleResult

**Comment by tabacha** [comment]
Es reicht wenn ein Admin weitere Leute zum Admin machen kann. Oder wir 
dokumentieren, was man in der Datenbank tun muss um einen User zum Admin zu 
machen. Dann kann man den Initialen Admin im Anschluss an das anlegen ggf. 
löschen.


Am 25. Juli 2019 08:45:02 schrieb bensteffen <notifications@github.com>:

**Comment by tabacha** [comment]
Ich habe dazu Ticket #18 aufgemacht. Sollen wir diesen Ticket schließen oder wollen wir was eleganteres als den Filter einbauen?
