### ISSUE TITLE
Mailversand Aktionspassword prüfen

### ISSUE THREAD

**Issue by tabacha** [ADFC-Hamburg/adfc-t30-api#64]
Vor dem Versand der E-Mail  muss geprüft werden ob die Aktion mit der Elternkammer noch läuft (Konfigurierbares Datum in den Settings) und wenn ja ob das Passort (Attibut password) (Settings) identisch ist.

Für Krankenhäuser + Pflegeheime gibt es kein Passwort.

**Comment by bensteffen** [comment]
Was soll passieren, wenn die Aktion noch läuft?

**Comment by tabacha** [comment]
Das Feld password mit dem in den Settings prüfen. Wenn identisch Mail 
versenden, wenn falsch: fehler

Am 2. Oktober 2019 19:21:57 schrieb bensteffen <notifications@github.com>:

**Comment by WiebkeADFC** [comment]
Das Aktionspasswort ist: kindersicher
es soll bis zum 17.11.2019 aktiv sein.
