### ISSUE TITLE
Andere ACL wenn eine E-Mail verschickt wurde

### ISSUE THREAD

**Issue by tabacha** [ADFC-Hamburg/adfc-t30-api#65]
Im Anschluss an den Mailversand soll:
1. verhindert werden, dass eine weitere E-Mail von diesen oder einem anderen Benutzer abgeschickt oder gespeichert wird.
2. Die weiteren Nutzer die angefangen haben eine E-Mail zu schreiben darüber informiert werden, dass jemand anders schneller war
3. Nur noch das Felder: status_text bearbeitet werden dürfen
4. Bei der verbundenen  streetSection sollen nur noch die Felder: street, house_no_from, house_no_to nicht mehr bearbeitet werden können, außer vom Admin.
5. Der Status bei der streetSection auf: Forderung wurde verschickt gestellt werden
6. Der Status bei der streetSection darf  nicht mehr auf: hier fehlt Tempo 30 gesetzt werden können. Hierfür braucht das Frontend noch einen API Call.
7. Jeder soll mail_body und mail_subject lesen dürfen. 
8. mail_start und mail_end sind nur für den Owner der Mail und Admins lesbar.

**Comment by bensteffen** [comment]
Zu 6.: Was für einen Call braucht das Frontend?

**Comment by tabacha** [comment]
In:  streetSection.id

Out: ist für diese StreetSection schon eine Mail verschickt worden?


Am 2. Oktober 2019 19:26:39 schrieb bensteffen <notifications@github.com>:

**Comment by tabacha** [comment]
Alternativ könnte das auch eine Information an der SteetSection sein, also z.B. 
mailSend: true
wenn eine E-Mail verschickt wurde.

**Comment by bensteffen** [comment]
Zu
> 2. Die weiteren Nutzer die angefangen haben eine E-Mail zu schreiben darüber informiert werden, dass jemand anders schneller war

Das hat sich wohl bereits mit dem Feld 'mail_sent' in 'demandedstreetsection' erledigt.

**Comment by tabacha** [comment]
> > 1. Die weiteren Nutzer die angefangen haben eine E-Mail zu schreiben darüber informiert werden, dass jemand anders schneller war
> 
> Mit informieren ist per E-Mail gemeint?

Ja

**Comment by tabacha** [comment]
Am 2019-10-07 21:23, schrieb bensteffen:
> Zu
> 
>> * Die weiteren Nutzer die angefangen haben eine E-Mail zu
>> schreiben darüber informiert werden, dass jemand anders schneller
>> war
> 
> Das hat sich wohl bereits mit dem Feld 'mail_sent' in
> 'demandedstreetsection' erledigt.
> 


Nein,

Benutzer A loggt sich ein und forumliert eine E-mail für einen 
Straßenabschnitt, schickt diesen aber noch nicht ab, weil er noch nicht 
fertig ist.

Dann loggt sich User B ein und forumliert eine zweite E-Mail für den 
gleichen Abschnitt und schickt diese gleich ab.

Jetzt soll User A einen E-Mail bekommen.

**Comment by bensteffen** [comment]
Erledigt:
> 1. verhindert werden, dass eine weitere E-Mail von diesen oder einem anderen Benutzer abgeschickt oder gespeichert wird.

**Comment by WiebkeADFC** [comment]
in der Testversion 45 geht das alles nicht.

**Comment by WiebkeADFC** [comment]
Julian und ich haben auch noch weiter über den Ablauf nach dem Versand einer Mail nachgedacht und folgende weitere Überlegungen: 

Angaben bei Details: 
Status ändern in: Hier fehlt Tempo 30, Forderungsmail abgeschickt

Button „Tempo 30 fordern“ weg,
Neuer Button: „Abgeschickte E-Mail ansehen“



Übersichten in Karte und Liste der Einrichtungen: 

Status ändern, siehe Issue #187 
Ableitung Kategorie Einrichtung von Status Straßenabschnitte.xlsx 



Bearbeiten, Straßenabschnitt: 

Für Bearbeitung sperren: 
Straße, Hausnummern

Status in Titel und Auswahlfeld ändern in: Hier fehlt Tempo 30, Forderungsmail abgeschickt
Status muss bearbeitbar bleiben für Eingabe, wenn Tempo 30 da ist. 

Alle anderen Felder bleiben bearbeitbar, weil Umstände sich ändern können.

Straßenabschnitt nicht mehr löschbar. 


Meine Forderungsmails: 

Aufführen als E-Mail abgeschickt

Bei anderen Leuten, die einen Entwurf zum selben Straßenabschnitt gespeichert haben, Hinweis: 
Für diesen Straßenabschnitt wurde zwischenzeitlich von einem anderen Nutzer eine Forderungsmail (verlink zum Archiv der versandten E-Mail) versandt. Deshalb kannst du diesen Entwurf leider nicht mehr versenden.

**Comment by tabacha** [comment]
Bitte keine alten Tickets wieder öffnen, nur weil es so bequm ist. Wir blicken dann nicht mehr durch. Bitte neue Tickets anlegen. Für jedes Problem ein eigenes.
