### ISSUE TITLE
Mails können wegen eines fehlerhaften Includes nicht an die Polizei verschickt werden

### ISSUE THREAD

**Issue by tabacha** [ADFC-Hamburg/adfc-t30-api#84]

**Comment by tabacha** [comment]
siehe #83

**Comment by WiebkeADFC** [comment]
Ich hatte nicht "aktion" als Stichwort verwendet, also kann es auch daran liegen, dass die Mail nicht versandt wurde. 
Der Test am Donnerstag findet doch nicht statt, weil an der Schule schon Tempo 30 ist.

**Comment by tabacha** [comment]
Das ist das Passwort auf dem Testsystem. Dort fehlt das Include nicht, aber da geht nie eine E-Mail an die Polizei. @WiebkeADFC  bitte keine Passwörter in Issue-Tracker ablegen.

**Comment by tabacha** [comment]
Danke fürs testen. Da ist noch ein Fehler, den wir beseitigen müssen.

**Comment by bensteffen** [comment]
Kann der Issue geschlossen werden?

**Comment by tabacha** [comment]
ja
