### ISSUE TITLE
Bug: Verfahren nach Absenden einer E-Mail läuft nicht in Testversion

### ISSUE THREAD

**Issue by WiebkeADFC** [ADFC-Hamburg/adfc-t30-api#86]
in #65 gab es nen Vorschlag, wie verfahren werden soll, wenn jemand eine E-Mail versand hat. Davon ist in der Testversion nichts zu sehen: 

Angaben bei Details:
Status ändern in: Hier fehlt Tempo 30, Forderungsmail abgeschickt

Button „Tempo 30 fordern“ weg,
Neuer Button: „Abgeschickte E-Mail ansehen“

Übersichten in Karte und Liste der Einrichtungen:

Status ändern, siehe Issue #187
Ableitung Kategorie Einrichtung von Status Straßenabschnitte.xlsx

Bearbeiten, Straßenabschnitt:

Für Bearbeitung sperren:
Straße, Hausnummern

Status in Titel und Auswahlfeld ändern in: Hier fehlt Tempo 30, Forderungsmail abgeschickt
Status muss bearbeitbar bleiben für Eingabe, wenn Tempo 30 da ist.

Alle anderen Felder bleiben bearbeitbar, weil Umstände sich ändern können.

Straßenabschnitt nicht mehr löschbar.

Meine Forderungsmails:

Aufführen als E-Mail abgeschickt

Bei anderen Leuten, die einen Entwurf zum selben Straßenabschnitt gespeichert haben, Hinweis:
Für diesen Straßenabschnitt wurde zwischenzeitlich von einem anderen Nutzer eine Forderungsmail (verlink zum Archiv der versandten E-Mail) versandt. Deshalb kannst du diesen Entwurf leider nicht mehr versenden.

**Comment by tabacha** [comment]
@WiebkeADFC  In das https://github.com/ADFC-Hamburg/adfc-t30-api/ Projekt Bitte nur Dinge rein, die das Backend betreffen. 

Und nur zu beschreiben, wie es laufen soll ist ziemlich doof, lieber was wir wo ändern sollen und was nicht geht. So kann ich und auch @bensteffen  nichts damit anfangen.

Sowas wie:

>Button „Tempo 30 fordern“ weg,
>Neuer Button: „Abgeschickte E-Mail ansehen“

ist Frontend und nicht Backend. Und das mache ich und gehört in das andere Projekt.

Wenn dir die Zuordnung Frontend / Backend nicht klar ist. Lieber Ticket im Frontend aufmachen.

Wenn Ihr bestimmte Dinge nicht testen könnt hilft es nicht, dass wir entwickler (statt den Bug zu Fixen, damit ihr testen könnt), eine Beschreibung bekommen was hinter dem Bug noch alles gehen sollte.
